### ISSUE TITLE
Issue with webpack

### ISSUE THREAD

**Issue by leeftk** [rouftom/truffle-react-material#1]
Hey Issa! Its Lee here from Truffle. I decided to add the issues that we found with the box here as its a bit easier to track and much easier to share code snippets then via email. Below is the issue I got after unboxing, installing dependencies and then running `npm run start`. I think it's an issue with webpack from some of the research I did but would like to hear your thoughts as well. Let me know what you think!

```
`> truffle-react-material@0.0.1 start /Users/leefaria/code/reprod/2022/05/16/ohgod
> webpack --mode development --content-base . --history-api-fallback

[webpack-cli] Error: Unknown option '--content-base'
[webpack-cli] Run 'webpack --help' to see available commands and options
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! truffle-react-material@0.0.1 start: `webpack --mode development --content-base . --history-api-fallback`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the truffle-react-material@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leefaria/.npm/_logs/2022-05-16T16_26_27_713Z-debug.log`
```

**Comment by rouftom** [comment]
Hi @leeftk,

Thank you for taking the time to view the project. Alright noted, I'll check that and fix it.

**Comment by rouftom** [comment]
Hello @leeftk,

I published a new version of the project taking into account your remarks and recommendations. I remain available if after the tests you still have comments.
