### ISSUE TITLE
404 when attempting to unbox

### ISSUE THREAD

**Issue by leeftk** [rouftom/truffle-react-material#2]
We had another dev on our team attempt to unbox the package and they got a 404 message. Not sure if this is just a one off but wanted to see if you could try unboxing on your machine in a new directory just to verify that everything is working.
```

`Cannot download "https://github.com/sass/node-sass/releases/download/v5.0.0/darwin-arm64-93_binding.node": 

HTTP error 404 Not Found`
```

**Comment by rouftom** [comment]
I removed this dependency from the project, I think it won't be a problem anymore.
