### ISSUE TITLE
Top repo a bit cluttered 

### ISSUE THREAD

**Issue by leeftk** [rouftom/truffle-react-material#3]
The root directory of this repo is a bit cluttered. Both react and truffle are there. I’d have react separated in a client folder. I'd suggest modeling the project structure after something like the truffle react box which can be found [here](https://github.com/truffle-box/react-box).

**Comment by rouftom** [comment]
Ok, I'll check the repo.

**Comment by leeftk** [comment]
Awesome thanks for addressing these issues! I'm taking a look at this today and will get back to you with comments.
