### ISSUE TITLE
Fallback to default websocket provider

### ISSUE THREAD

**Issue by leeftk** [rouftom/truffle-react-material#4]
<img width="1439" alt="Screen Shot 2022-06-09 at 11 50 01 AM" src="https://user-images.githubusercontent.com/40748420/172890245-34a54b4a-81c1-4e62-995b-2119616482bc.png">

I found another issue. It seems like it keeps falling back to the default websocket provider instead of going with the provider that I set to Metamask. In other words it only works if I open up a ganache port at `7545`. In theory it should use whatever I set in my `truffle-config.js` as the network. Do you mind taking a look at this and letting me know if you're getting the same issue? I attached a screenshot in hopes that it will help. Thanks!!

**Comment by rouftom** [comment]
Hello @leeftk,

Indeed you are right, I tested and I had the same error as you. I fixed the bug and the box now manages to connect to Metamask without problem. Here is a screenshot of the demo.

![Capture d’écran du 2022-06-12 03-55-00](https://user-images.githubusercontent.com/12144793/173212357-6c9cb656-ad4b-43ee-8a42-aad63b5f7ba9.png)

**Comment by rouftom** [comment]
I submit a new commit which fixed the bug. I remain at your disposal for any further remark or observation.
