### ISSUE TITLE
Prettier JS

### ISSUE THREAD

**Issue by leeftk** [rouftom/truffle-react-material#6]
Seems like there's a few formatting issues in the code. If you just want to install something like prettier JS and run it in your root directory is should easily fix all these.

https://github.com/rouftom/truffle-react-material/blob/main/client/src/ui/CircularLoaderUI.jsx

**Comment by rouftom** [comment]
I just corrected the formatting of the file. My editor (already embeds Prettier) hadn't formatted it correctly.
